server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    hikari:
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.25.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  worker:
    workerId: 1
    datacenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    notifyUrl:  http://75f39y.natappfree.cc/WeChatPayNotify #http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify
    httpConnectTimeoutMs: 1000 #連接超时时间
    httpReadTimeoutMs: 3000 #读取超时
logging:
  level:
    com.leyou: debug