server:
  port: 8081
spring:
  rabbitmq:
    #host: 192.168.25.129
    #username: /leyou
    #password: leyou
    #virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
      retry:
        enabled: true
    publisher-confirms: true
    addresses: 192.168.25.129,192.168.25.130,192.168.25.131
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: root
    url: jdbc:mysql://127.0.0.1:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    com.leyou.item: debug