server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: root
    url: jdbc:mysql://127.0.0.1:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1